#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config-dist.php" --destination="$install_dir/data/config.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
